### ISSUE TITLE
CSRF hits when using load balancer

### ISSUE THREAD

**Issue by kapolos** [untitaker/mysteryshack#65]
I am trying to put a [rancher](http://rancher.com/rancher/) [load balancer](http://docs.rancher.com/rancher/v1.3/en/rancher-services/load-balancer/) in front of mysteryshack.

The load balancer does the SSL termination and reverse proxy to the mysteryshack container port (which is not exposed to the outside world). When I go to https://mysteryshackdomain/ I see the login page normally but after I enter my credentials, I get `CSRF detected.`. Any advice on resolving this? 📲

**Comment by kapolos** [comment]
Update: I've switched to `caddy`, enabled the proxy setting in the mysteryshack config file, set the proper headers in caddy, same result.

These docker logs appear immediately after mysteryshack starts running - **before** I make any request via the proxy.
```
1/14/2017 6:29:46 PMGenerating session keys...
1/14/2017 6:29:46 PMListening on: http://0.0.0.0:6767
1/14/2017 6:29:54 PMthread '<unnamed>' panicked at 'Missing header: "X-Forwarded-Host". Turn off use_proxy_headers or set proxy headers.', src/mysteryshack/web/utils.rs:39
1/14/2017 6:29:54 PMnote: Run with `RUST_BACKTRACE=1` for a backtrace.
1/14/2017 6:29:58 PMthread '<unnamed>' panicked at 'Missing header: "X-Forwarded-Host". Turn off use_proxy_headers or set proxy headers.', src/mysteryshack/web/utils.rs:39
1/14/2017 6:29:58 PMthread '<unnamed>' panicked at 'Missing header: "X-Forwarded-Host". Turn off use_proxy_headers or set proxy headers.', src/mysteryshack/web/utils.rs:39
1/14/2017 6:30:00 PMthread '<unnamed>' panicked at 'Missing header: "X-Forwarded-Host". Turn off use_proxy_headers or set proxy headers.', src/mysteryshack/web/utils.rs:39
1/14/2017 6:30:05 PMthread '<unnamed>' panicked at 'Missing header: "X-Forwarded-Host". Turn off use_proxy_headers or set proxy headers.', src/mysteryshack/web/utils.rs:39
1/14/2017 6:30:06 PMthread '<unnamed>' panicked at 'Missing header: "X-Forwarded-Host". Turn off use_proxy_headers or set proxy headers.', src/mysteryshack/web/utils.rs:39
1/14/2017 6:30:07 PMthread '<unnamed>' panicked at 'Missing header: "X-Forwarded-Host". Turn off use_proxy_headers or set proxy headers.', src/mysteryshack/web/utils.rs:39
1/14/2017 6:38:17 PMGenerating session keys...
1/14/2017 6:38:17 PMListening on: http://0.0.0.0:6767
```

Afterwards, when I load the site and try to log in, no further logs appear.

**Comment by untitaker** [comment]
As explained in the config file you need to set the appropriate headers or disable proxy support entirely (in that case you need to forward the original `Host` header)

**Comment by kapolos** [comment]
Well, that's the thing, the headers are set - this is the `caddy` config:

```
remotestorage.domain.com {
 
   proxy / mysteryshack.remotestorage:6767 {
     websocket
     transparent
     header_upstream X-Forwarded-Host {host}
     header_upstream X-Forwarded-Port {port}
   }
 
   gzip
 
   tls nospamplease@domain.com
 }
```

As per the [docs](https://caddyserver.com/docs/proxy), `transparent` is a shorthand for:
```
header_upstream Host {host}
header_upstream X-Real-IP {remote}
header_upstream X-Forwarded-For {remote}
header_upstream X-Forwarded-Proto {scheme}
```

Those, along with the added
```
     header_upstream X-Forwarded-Host {host}
     header_upstream X-Forwarded-Port {port}
```

should make the proxy support work, no? If so, I think it's a bug, rather than a config issue.

**Comment by untitaker** [comment]
In master I added extra code for better error messages, please check again. It
might be that your host header is not in the expected format

**Comment by untitaker** [comment]
@kapolos any update on this?

**Comment by kapolos** [comment]
@untitaker Hard week, hadn't had the chance yet, hopefully by late tomorrow.

**Comment by kapolos** [comment]
![image](https://cloud.githubusercontent.com/assets/10794126/22410571/fe6d0eea-e667-11e6-954e-4809050303ef.png)

![image](https://cloud.githubusercontent.com/assets/10794126/22410578/182222a8-e668-11e6-8153-ba92988396de.png)

**Comment by untitaker** [comment]
That appears to be the wrong portion of the error log, since the CSRF error message doesn't return a 404 status code.

**Comment by kapolos** [comment]
That's all there was. I'll retry just in case though.

**Comment by pwFoo** [comment]
Any progress with that issue? I have the same one (caddy reverse proxy, CSRF detected).

**Comment by untitaker** [comment]
I'm sorry, I don't maintain this anymore.
