### ISSUE TITLE
failed to run custom build command for `openssl-sys v0.9.7`

### ISSUE THREAD

**Issue by Antoxyde** [untitaker/mysteryshack#72]
debian 8 up to date
```
cargo build --release
   Compiling openssl-sys v0.9.7
   Compiling clap v2.20.3
error: failed to run custom build command for `openssl-sys v0.9.7`
process didn't exit successfully: `/var/www/note/mysteryshack/target/release/build/openssl-sys-a41752c102bebd07/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"`: No such file or directory (os error 2)"', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
  10: build_script_build::main
  11: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  12: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  13: __libc_start_main
  14: <unknown>
```

I got openssl :
```
➜  mysteryshack git:(master) openssl version                 
OpenSSL 1.0.1t  3 May 2016
```
I'm new to rust and i could'nt find any answer on the net :(

**Comment by untitaker** [comment]
> "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"`: No such file or directory (os error 2)"

I suspect that the pkg-config command is missing on your system.

**Comment by Antoxyde** [comment]
Ok you were right ^^
Thanks the compilation ended well!
